#!/bin/bash

build() {
  add_binary /usr/bin/lsblk
  add_binary /usr/bin/lsmod
  add_binary /usr/bin/dmesg
  add_binary /usr/bin/losetup
  add_binary /usr/bin/mount
  add_binary /usr/bin/umount
  add_full_dir /usr/share/asahi-scripts
  add_runscript
}

help() {
  cat <<HELPEOF
Find the USB volume labelled OMARCHYISO, loop-mount root.img, overlay a
tmpfs, print a readiness line, and keep pid 1 alive. Does not switch_root.
HELPEOF
}
