#!/bin/bash

build() {
  local here
  here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  add_binary /usr/bin/lsblk
  add_binary /usr/bin/lsmod
  add_binary /usr/bin/dmesg
  add_binary /usr/bin/losetup
  add_binary /usr/bin/mount
  add_binary /usr/bin/umount
  add_binary /usr/bin/switch_root
  add_full_dir /usr/share/asahi-scripts
  add_file "$here/../../usb/modprobe.d/hid_apple.conf" /etc/modprobe.d/hid_apple.conf
  add_file "$here/../../usb/modprobe.d/asahi-notch.conf" /etc/modprobe.d/asahi-notch.conf
  add_runscript
}

help() {
  cat <<HELPEOF
Find the btrfs payload labelled OMARCHYLIVE, mount subvol=@, overlay a
tmpfs, and switch_root into /sbin/init on that overlay.
HELPEOF
}
